#!/usr/bin/env python3
"""
e3_assemble.py — build the E3 blind bake-off packet from curated real pieces
and skill-generated pieces. Randomizes A/B per comparison; writes the blind
packet + rating sheet (safe to open) and a SEALED answer key (do not open
until ratings are done).
"""

import json
import random
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
E3 = ROOT / "_active" / "elevation-track" / "e3"

EXPERT_LABEL = {
    "lara-acosta-linkedin-mastery": "Lara Acosta (LinkedIn post)",
    "luke-iha-copy-blocks": "Luke Iha (DR ad copy)",
    "alex-hormozi-business": "Alex Hormozi (post/book passage)",
    "andrew-stanton-audience-engineering": "Andrew Stanton (storytelling explanation)",
    "alex-suzuki-digital-product-revenue-os": "Alex Suzuki / X_FINALBOSS (X post)",
}


def main():
    real = {(p["skill"], p["idx"]): p
            for p in json.loads((E3 / "real-pieces.json").read_text())["pieces"]}
    gen = {}
    for skill in EXPERT_LABEL:
        data = json.loads((E3 / f"gen-{skill}.json").read_text())
        for p in data["pieces"]:
            gen[(skill, p["idx"])] = p["text"]

    rng = random.SystemRandom()
    packet = ["# E3 Blind Bake-Off Packet",
              "",
              "For each comparison: one piece is the real expert's published work, "
              "one was generated by the corresponding Antigravity skill. Order is random per comparison. "
              "Fill in `E3-rating-sheet.md` as you go. Do NOT open `E3-ANSWER-KEY-SEALED.json` until done.",
              ""]
    sheet = ["# E3 Rating Sheet",
             "",
             "Per comparison, answer both questions. Gut verdict beats deliberation — "
             "your taste signature is bimodal, trust the fast read.",
             "",
             "| # | Expert | Real one is (A/B/can't tell) | Better one is (A/B/tie) | Notes |",
             "|---|--------|------------------------------|--------------------------|-------|"]
    key = []

    n = 0
    for skill, label in EXPERT_LABEL.items():
        packet.append(f"\n## {label}\n")
        for idx in (1, 2, 3):
            n += 1
            r = real[(skill, idx)]
            g = gen[(skill, idx)]
            real_is_a = rng.random() < 0.5
            a_text, b_text = (r["text"], g) if real_is_a else (g, r["text"])
            packet += [f"### Comparison {n}", "",
                       "**Piece A:**", "", "```", a_text, "```", "",
                       "**Piece B:**", "", "```", b_text, "```", ""]
            sheet.append(f"| {n} | {label.split(' (')[0]} |  |  |  |")
            key.append({"comparison": n, "skill": skill, "piece_idx": idx,
                        "real": "A" if real_is_a else "B",
                        "real_source": r["source"], "real_confidence": r["confidence"]})

    (E3 / "E3-blind-packet.md").write_text("\n".join(packet))
    (E3 / "E3-rating-sheet.md").write_text("\n".join(sheet) + "\n")
    (E3 / "E3-ANSWER-KEY-SEALED.json").write_text(json.dumps(key, indent=1))
    print(f"assembled {n} comparisons → E3-blind-packet.md, E3-rating-sheet.md, E3-ANSWER-KEY-SEALED.json")


if __name__ == "__main__":
    main()
