#!/usr/bin/env python3
"""
generate_slash_commands.py — keep SLASH_COMMANDS.md complete and current.

Strategy (non-destructive):
  1. Preserve the entire hand-curated SLASH_COMMANDS.md verbatim (all curated
     descriptions, the Natural-Language-Triggers table, How-I-Write OS, Fork
     Harvest — none of it is touched).
  2. Scan every real command source (.agent/workflows/*.md + .claude/commands/*.md),
     union by command name, pull the best available one-line description.
  3. Append a single auto-generated region ("Complete Command Index — Everything
     Else") holding every command NOT already documented above, grouped by
     expert-family / theme, in the same `| Command | What It Does |` format.
  4. Idempotent: the appended region is fenced by sentinel comments and rebuilt
     on every run, so re-running never duplicates.

Run:  python3 execution/generate_slash_commands.py
      python3 execution/generate_slash_commands.py --check   # report only, no write
"""
from __future__ import annotations
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MD = ROOT / "SLASH_COMMANDS.md"
WF_DIR = ROOT / ".agent" / "workflows"
CMD_DIR = ROOT / ".claude" / "commands"

BEGIN = "<!-- AUTO-INDEX:BEGIN (generated by execution/generate_slash_commands.py — do not edit by hand) -->"
END = "<!-- AUTO-INDEX:END -->"

# ── description extraction ────────────────────────────────────────────────
FRONTMATTER_DESC = re.compile(r'^description:\s*(.+?)\s*$', re.MULTILINE)


def clean(text: str) -> str:
    text = text.strip().strip('"').strip("'").strip()
    text = re.sub(r'\s+', ' ', text)
    return text


def yaml_desc(fm: str) -> str:
    """Pull `description:` from a YAML frontmatter block, handling both inline
    values and `|`/`>` block scalars (text on following indented lines)."""
    lines = fm.splitlines()
    for i, line in enumerate(lines):
        m = re.match(r'^description:\s*(.*)$', line)
        if not m:
            continue
        val = m.group(1).strip().strip('"').strip("'").strip()
        if re.fullmatch(r'[|>][-+]?', val) or val == "":
            # block scalar — gather following indented lines
            block = []
            for nxt in lines[i + 1:]:
                if nxt.strip() == "":
                    if block:
                        break
                    continue
                if nxt.startswith((" ", "\t")):
                    block.append(nxt.strip())
                else:
                    break
            return clean(" ".join(block))
        return clean(val)
    return ""


def _slug(s: str) -> str:
    return re.sub(r'[^a-z0-9]+', '-', s.lower()).strip('-')


def extract_description(path: Path, name: str = "", _depth: int = 0) -> str:
    try:
        raw = path.read_text(encoding="utf-8", errors="replace")
    except Exception:
        return ""
    # 1. frontmatter description: — fenced (---) or unfenced YAML at file head
    fm = None
    if raw.startswith("---"):
        end = raw.find("\n---", 3)
        if end != -1:
            fm = raw[3:end]
    if fm is None:
        # unfenced: treat the leading run of "key: value" lines as frontmatter
        head_lines = []
        for line in raw.splitlines():
            if re.match(r'^[a-zA-Z_][\w-]*:\s', line) or (head_lines and line.startswith((' ', '"', '-', '['))):
                head_lines.append(line)
            else:
                break
        fm = "\n".join(head_lines)
    if fm:
        d = yaml_desc(fm)
        if d:
            return d
    # 2. command-wrapper pattern: "... — <desc>"
    m = re.search(r'Read and execute the workflow at `[^`]+`\s*[—-]\s*(.+)', raw)
    if m:
        return clean(m.group(1)).strip('"')
    # 2b. skill-command shim: resolve to the target SKILL.md description
    m = re.search(r'Load and embody the skill at `(skills/[^`]+/SKILL\.md)`', raw)
    if m:
        skill = ROOT / m.group(1)
        if skill.exists():
            sraw = skill.read_text(encoding="utf-8", errors="replace")
            sfm = sraw[3:sraw.find("\n---", 3)] if sraw.startswith("---") else sraw
            d = yaml_desc(sfm)
            if d:
                return d
    # 2c. "Run the **Bold Title** workflow" convention (prefer local title)
    m = re.search(r'Run the \*\*(.+?)\*\*', raw)
    if m:
        d = clean(m.group(1))
        if len(d) >= 6 and _slug(d) != name:
            return d
    # strip frontmatter from the body before prose/heading scanning
    body = raw
    if raw.startswith("---"):
        e = raw.find("\n---", 3)
        if e != -1:
            body = raw[e + 4:]

    # 3. first substantive prose line (incl. blockquote) under the title
    for line in body.splitlines():
        s = line.strip()
        if not s or s.startswith(("#", "|", "```", "---", "<!--")):
            continue
        s = re.sub(r'^>\s*', '', s)              # unwrap blockquote
        if re.match(r'^[a-zA-Z_][\w-]*:\s', s):  # skip stray yaml
            continue
        if re.match(r'^[-*]?\s*\*\*[^*]+\*\*\s*:', s):  # skip bold metadata labels
            continue
        if re.match(r'^(\d+[.)]|[-*+])\s', s):          # skip list items
            continue
        if len(s) >= 20 and " " in s and _slug(s) != name:
            return clean(s)

    # 4. fallback: first heading that isn't the name or a generic section label
    GENERIC = {"trigger", "workflow", "usage", "quick use", "quick start",
               "instructions", "produces", "output", "overview", "steps",
               "context required", "when to use", "inputs", "process",
               "requirements", "notes", "example", "examples", "goal"}
    for line in body.splitlines():
        line = line.strip()
        if line.startswith("#"):
            h = clean(line.lstrip("#").strip())
            h = re.sub(r'^[/`]+|[`]+$', '', h)
            if (h and not h.startswith("PHASE")
                    and not re.match(r'^[a-zA-Z_][\w-]*:\s', h)
                    and _slug(h) != name
                    and h.lower() not in GENERIC):
                return h

    # 5. last resort: resolve a "skills/.../workflows/X.md" pointer if present
    if _depth < 2:
        m = re.search(r'`(skills/[^`]+/workflows/[^`]+\.md)`', raw)
        if m:
            tgt = ROOT / m.group(1)
            if tgt.exists() and tgt != path:
                d = extract_description(tgt, name, _depth + 1)
                if d and _slug(d) != name:
                    return d
    return ""


def best_description(name: str) -> str:
    # prefer the workflow definition, fall back to the command wrapper
    for base in (WF_DIR, CMD_DIR):
        p = base / f"{name}.md"
        if p.exists():
            d = extract_description(p, name)
            if d and _slug(d) != name:
                # truncate absurdly long descriptions to one readable line
                if len(d) > 240:
                    d = d[:237].rstrip() + "..."
                return d
    return "(workflow — see file for details)"


# ── collect universe + already-documented ────────────────────────────────
def all_command_names() -> set[str]:
    names = set()
    for base in (WF_DIR, CMD_DIR):
        if base.exists():
            for p in base.glob("*.md"):
                names.add(p.stem)
    return names


def documented_in_md(md_text: str) -> set[str]:
    # strip the auto region before scanning so its own entries don't count
    if BEGIN in md_text:
        md_text = md_text.split(BEGIN)[0]
    return set(re.findall(r'`/([a-z0-9][a-z0-9-]*)`', md_text))


# ── expert-family grouping for the appendix ───────────────────────────────
# display name -> list of prefixes (matched as "<prefix>-" or exact)
FAMILIES: list[tuple[str, list[str]]] = [
    ("✍️ Copywriting — Jason Fladlien", ["fladlien"]),
    ("✍️ Copywriting — Luke Iha", ["luke-iha", "luke"]),
    ("✍️ Copywriting — Stefan Georgi", ["georgi"]),
    ("✍️ Copywriting — Sam Parr", ["sam-parr"]),
    ("🎬 Screenwriting & Story — Noah Hawley", ["hawley"]),
    ("🎬 Story Craft — Andrew Stanton", ["stanton"]),
    ("🎬 Story Craft — Michael Connelly", ["connelly"]),
    ("🎬 Story Craft — Wright Thompson", ["wright"]),
    ("🎬 Story Craft — Eric Roth", ["roth"]),
    ("🎬 Story Craft — Sander Runia", ["runia"]),
    ("✒️ Really-Real Writing — Anne Lamott", ["lamott", "really-real"]),
    ("🧘 Dharma & Identity — Dr. K", ["drk", "dr-k"]),
    ("📖 Teach-to-Sell — Omar Eltakrori", ["oe"]),
    ("📖 Teaching Business — Omar Eddaoudi", ["omar-eddaoudi", "omar"]),
    ("🏛️ Brand & Positioning — Oren Klaff", ["oren"]),
    ("🏛️ Brand — Seth Godin", ["godin", "seth-godin"]),
    ("🏛️ Business Growth — Donald Miller", ["donald-miller", "storybrand"]),
    ("📈 LinkedIn — Diandra Escobar", ["diandra"]),
    ("📈 LinkedIn — Lara Acosta", ["lara-acosta", "lara"]),
    ("📈 Personal Brand — Jun Yuh", ["junyuh", "jun-yuh"]),
    ("🏠 Real Estate — Enrico Incarnati", ["enrico"]),
    ("👕 Buyer-Trigger Merch — Meg Heckman", ["meg"]),
    ("🔤 Word & Novelty — Kallaway", ["kallaway", "novelty", "word"]),
    ("🎨 Design — Satori Graphics", ["satori"]),
    ("🎨 Design.md & Systems", ["design"]),
    ("🚀 Launch & Product — Alex Suzuki", ["suzuki"]),
    ("🤖 AI Orchestration — Mark Kashef", ["mark-kashef"]),
    ("🤖 AI Systems — Nate B. Jones", ["nate-b-jones", "nate"]),
    ("🤖 Agentic Workflows — Nick Saraev", ["nick-saraev"]),
    ("📊 Newsletter & Positioning — Nicolas Cole", ["nicolas-cole"]),
    ("💡 Taste & Craft OS", ["taste"]),
    ("💡 Depth & Interiority Engine", ["depth"]),
    ("💡 Proof Architecture", ["proof"]),
    ("💡 Belief & Perception", ["belief", "perception"]),
    ("💡 Obsession & Attention", ["obsession", "attention"]),
    ("⚡ Velocity & Scaling", ["velocity", "quantity"]),
    ("📇 24 Assets OS — Daniel Priestley", ["24-assets", "daniel-priestley"]),
    ("🧩 JW Propaganda Engine", ["jw"]),
]

# experts referenced by a single-token skill name (extraction personas) get a
# generic bucket; everything else falls to the alphabetical long-tail.


def family_for(name: str) -> str | None:
    for display, prefixes in FAMILIES:
        for pre in prefixes:
            if name == pre or name.startswith(pre + "-"):
                return display
    return None


_SKILL_REF_RE = re.compile(r"skills/([^/]+)/workflows/")


def skill_family_of(name: str) -> str | None:
    """The skill a command's wrapper executes into, if any.

    Menu wrappers embed the full `skills/<skill>/workflows/<file>.md` path, so
    the family is read off disk rather than guessed from the command's prefix.
    """
    p = WF_DIR / f"{name}.md"
    if not p.exists():
        return None
    m = _SKILL_REF_RE.search(p.read_text(encoding="utf-8", errors="replace"))
    if not m:
        return None
    skill = m.group(1)
    # Some workflow docs contain template EXAMPLES like `skills/[skill-name]/...`.
    # Only a directory that actually exists counts as a family.
    return skill if (ROOT / "skills" / skill).is_dir() else None


def build_appendix(missing: dict[str, str]) -> str:
    """Family-rollup index, not one row per command.

    WHY (2026-07-25, Arsenal Loop): this file is a DOCUMENT — the model reads it
    on demand per CLAUDE.md, and nothing fires from it (the native `/` menu is
    powered by .claude/commands/*.md, which stays complete). Emitting one
    described row per command took it to 592KB, well past the 350KB bloat
    threshold health_metrics.py flags, making a single read a context grenade.

    So: skill families collapse to one row each (count + front door + how to
    expand), and standalone commands list as bare names. Nothing becomes
    unreachable — `/arsenal` serves descriptions on demand at a few hundred
    tokens instead of hundreds of kilobytes.
    """
    by_skill: dict[str, list[str]] = {}
    standalone: list[str] = []
    for name in sorted(missing):
        skill = skill_family_of(name)
        if skill:
            by_skill.setdefault(skill, []).append(name)
        else:
            standalone.append(name)

    lines: list[str] = [BEGIN, ""]
    total = len(missing)
    lines.append(f"## 📚 Complete Command Index — Everything Else ({total})")
    lines.append("")
    lines.append(
        "Every command on disk that isn't already described in a curated section above. "
        "Auto-generated by `execution/generate_slash_commands.py`.\n\n"
        "**All of these fire right now** — the `/` typeahead in Claude Code reads "
        "`.claude/commands/`, which is complete. This page is a map, not the menu. "
        "Expert-skill commands are rolled up by family so the file stays cheap to read; "
        "for descriptions, run **`/arsenal <what you're trying to do>`** or "
        "`python3 execution/arsenal.py --family <skill>`."
    )
    lines.append("")

    if by_skill:
        lines.append(f"### 🎓 Expert Skill Families ({sum(len(v) for v in by_skill.values())} "
                     f"commands across {len(by_skill)} families)")
        lines.append("")
        lines.append("| Family | Commands | Examples | See all |")
        lines.append("|--------|----------|----------|---------|")
        for skill in sorted(by_skill):
            cmds = by_skill[skill]
            front = f"`/{skill}`" if (CMD_DIR / f"{skill}.md").exists() else "—"
            examples = ", ".join(f"`/{c}`" for c in cmds[:3])
            if len(cmds) > 3:
                examples += ", …"
            lines.append(f"| {front} **{skill}** | {len(cmds)} | {examples} "
                         f"| `/arsenal --family {skill}` |")
        lines.append("")

    if standalone:
        lines.append(f"### 🗂️ Standalone Workflows — A–Z ({len(standalone)})")
        lines.append("")
        lines.append("Names only — run `/arsenal <task>` for what each one does.")
        lines.append("")
        current = ""
        bucket: list[str] = []
        for c in standalone:
            letter = c[0].upper()
            if letter != current:
                if bucket:
                    lines.append(f"**{current}** · " + " · ".join(f"`/{x}`" for x in bucket))
                    lines.append("")
                current, bucket = letter, []
            bucket.append(c)
        if bucket:
            lines.append(f"**{current}** · " + " · ".join(f"`/{x}`" for x in bucket))
            lines.append("")

    lines.append(END)
    return "\n".join(lines)


def main() -> int:
    check = "--check" in sys.argv
    md_text = MD.read_text(encoding="utf-8")

    # lift the quick-tip footer from anywhere in the doc so it re-emits last
    footer_re = re.compile(r'^> \*\*Quick tip:\*\*.*$', re.MULTILINE)
    fm = footer_re.search(md_text)
    footer = fm.group(0) if fm else ""
    # strip any prior auto region, then rebuild head
    if BEGIN in md_text:
        head = md_text.split(BEGIN)[0]
    else:
        head = md_text
    if footer:
        head = footer_re.sub("", head)
    # drop trailing "---" separators left behind by removed blocks
    head = re.sub(r'(\n---\s*)+$', '', head).rstrip()

    universe = all_command_names()
    documented = documented_in_md(head)
    missing_names = sorted(universe - documented)
    missing = {n: best_description(n) for n in missing_names}

    print(f"total commands on disk : {len(universe)}")
    print(f"already documented     : {len(documented)}")
    print(f"missing (to append)    : {len(missing)}")
    stale = sorted(documented - universe)
    if stale:
        print(f"documented but no file : {len(stale)} -> {', '.join(stale[:10])}"
              + (" ..." if len(stale) > 10 else ""))

    if check:
        return 0

    appendix = build_appendix(missing)
    new_text = head + "\n\n---\n\n" + appendix + "\n"
    if footer:
        new_text += "\n---\n\n" + footer.strip() + "\n"

    # refresh the headline count on line 1
    grand_total = len(documented | universe)
    new_text = re.sub(
        r'# 🚀 Antigravity Workflows — Complete Index \(\d+ Commands\)',
        f'# 🚀 Antigravity Workflows — Complete Index ({grand_total} Commands)',
        new_text, count=1,
    )

    MD.write_text(new_text, encoding="utf-8")
    print(f"wrote {MD} ({grand_total} commands total)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
