#!/usr/bin/env python3
"""
plugin_build.py — compile a repo bundle into an installable Claude Code plugin.

WHY THIS EXISTS
---------------
`skills/forge-os/references/plugin-forge-lift-plan.md` claimed "the lift adds zero
new engines," listing plugin_readiness_audit.py, plugin-dev:plugin-validator, and
renaissance_audit.py as the toolchain. Those are a SCORER, a VALIDATOR, and an
AUDIT. None of them emits `.claude-plugin/plugin.json`. The packaging step the
plan authorized had no owner — which is why Plugin Forge sat at "engine ready"
for so long. This is that step.

DESIGN RULES (all from the lift plan's own guardrails)
-------------------------------------------------------
  * REGENERATED, NEVER HAND-EDITED. The repo is the single source of truth; a
    plugin is a build artifact. Hand-editing one guarantees the "version drift vs
    repo originals" failure the plan names.
  * LOCAL PATH ONLY. Output goes to `plugins/` inside the repo. No global writes,
    no marketplace — marketplace stays out of scope regardless of this lift.
  * READINESS-GATED. Only workflows the readiness audit scores PACKAGE NOW (>=80)
    are packaged. Packaging a REFERENCE-ONLY workflow produces a plugin that
    proves nothing.
  * ${CLAUDE_PLUGIN_ROOT} FOR EVERY INTRA-PLUGIN PATH. Hardcoded absolute paths
    break on any machine but the one that built them.

Usage:
    python3 execution/plugin_build.py build --bundle operator-core
    python3 execution/plugin_build.py build --bundle operator-core --force
    python3 execution/plugin_build.py validate plugins/antigravity-operator-core
    python3 execution/plugin_build.py clean plugins/antigravity-operator-core
"""
from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
from pathlib import Path
from typing import Any, Dict, List

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "execution"))

import plugin_readiness_audit as readiness  # noqa: E402

PLUGINS_DIR = ROOT / "plugins"
WF_DIR = ROOT / ".agent" / "workflows"
SKILLS_DIR = ROOT / "skills"
PLUGIN_ROOT_VAR = "${CLAUDE_PLUGIN_ROOT}"
BUILD_STAMP = "<!-- BUILD ARTIFACT — regenerated by execution/plugin_build.py. Do not hand-edit. -->"
PACKAGE_NOW_FLOOR = 80


# ──────────────────────────────────────────────────────────────────────────
# helpers
# ──────────────────────────────────────────────────────────────────────────

def _read(p: Path) -> str:
    try:
        return p.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ""


def _frontmatter_desc(text: str) -> str:
    m = re.search(r"^description:\s*(.+?)\s*$", text, re.M)
    return m.group(1).strip().strip('"').strip("'") if m else ""


def sanitize(text: str) -> str:
    """Replace the author's absolute repo path with a portable env reference.

    120 workflows hardcode `/Users/farricecain/Google Antigravity`. Shipping that
    in a plugin leaks a home directory and breaks on every other machine — the
    "portability lock-in" risk the lift plan names.

    It becomes $ANTIGRAVITY_ROOT, NOT ${CLAUDE_PLUGIN_ROOT}: these paths refer to
    the REPO, not to the plugin. Collapsing the two would silently redirect
    repo-root semantics at the plugin's own directory and quietly break behavior.
    """
    return text.replace(str(ROOT), "$ANTIGRAVITY_ROOT")


def _strip_frontmatter(text: str) -> str:
    if text.startswith("---"):
        end = text.find("\n---", 3)
        if end != -1:
            return text[end + 4:].lstrip("\n")
    return text


def eligible(bundle: str) -> tuple[List[readiness.Score], List[readiness.Score]]:
    """(package-now, rejected) for a bundle, scored by the repo's own gate."""
    counts = readiness.routing_counts()
    scores = [readiness.score_candidate(n, counts)
              for n in readiness.BUNDLE_CANDIDATES[bundle]]
    ok = [s for s in scores if s.total >= PACKAGE_NOW_FLOOR]
    no = [s for s in scores if s.total < PACKAGE_NOW_FLOOR]
    return ok, no


# ──────────────────────────────────────────────────────────────────────────
# emit
# ──────────────────────────────────────────────────────────────────────────

def emit_command(score: readiness.Score, out: Path) -> str | None:
    """One plugin command per packaged workflow.

    The command carries the workflow BODY, not a pointer back into the repo: an
    installed plugin must work without the repo present, or it is not portable.
    """
    src = WF_DIR / f"{score.name}.md"
    if not src.exists():
        return None
    raw = _read(src)
    desc = _frontmatter_desc(raw) or score.name.replace("-", " ")
    body = sanitize(_strip_frontmatter(raw))
    (out / "commands").mkdir(parents=True, exist_ok=True)
    (out / "commands" / f"{score.name}.md").write_text(
        f"---\nname: {score.name}\ndescription: {json.dumps(desc)[1:-1]}\n---\n"
        f"{BUILD_STAMP}\n\n{body}\n", encoding="utf-8")
    return score.name


def emit_skill(skill: str, out: Path, prompt: Path | None) -> str | None:
    """Carry a repo skill across, plus one prompts-v2 execution prompt (F-CRE)."""
    src = SKILLS_DIR / skill / "SKILL.md"
    if not src.exists():
        return None
    dest = out / "skills" / skill
    dest.mkdir(parents=True, exist_ok=True)
    raw = _read(src)
    desc = _frontmatter_desc(raw) or skill
    body = sanitize(_strip_frontmatter(raw))
    extra = ""
    if prompt and prompt.exists():
        (dest / "references").mkdir(exist_ok=True)
        (dest / "references" / prompt.name).write_text(sanitize(_read(prompt)), encoding="utf-8")
        extra = (f"\n\n## Bundled Execution Prompt\n\n"
                 f"Read `{PLUGIN_ROOT_VAR}/skills/{skill}/references/{prompt.name}` "
                 f"and run it as written before producing output.\n")
    (dest / "SKILL.md").write_text(
        f"---\nname: {skill}\ndescription: {json.dumps(desc)[1:-1]}\nversion: 1.0.0\n---\n"
        f"{BUILD_STAMP}\n\n{body}{extra}\n", encoding="utf-8")
    return skill


def emit_hook(out: Path) -> None:
    """F-SYS fixture: a real hook whose script must resolve ${CLAUDE_PLUGIN_ROOT}."""
    hooks = out / "hooks"
    (hooks / "scripts").mkdir(parents=True, exist_ok=True)
    (hooks / "hooks.json").write_text(json.dumps({
        "SessionStart": [{
            "hooks": [{
                "type": "command",
                "command": f"bash {PLUGIN_ROOT_VAR}/hooks/scripts/plugin-root-probe.sh",
                "timeout": 5,
            }],
        }],
    }, indent=2) + "\n", encoding="utf-8")
    (hooks / "scripts" / "plugin-root-probe.sh").write_text(
        '#!/bin/bash\n'
        '# F-SYS fixture probe. Echoes the resolved plugin root so the fixture can\n'
        '# prove ${CLAUDE_PLUGIN_ROOT} expands after a local install. If this prints\n'
        '# an empty path, plugin path resolution is broken and the lift fails.\n'
        'if [ -z "$CLAUDE_PLUGIN_ROOT" ]; then\n'
        '  echo "PLUGIN ROOT PROBE: FAIL — CLAUDE_PLUGIN_ROOT unset"\n'
        'else\n'
        '  echo "PLUGIN ROOT PROBE: ok — $CLAUDE_PLUGIN_ROOT"\n'
        'fi\n', encoding="utf-8")
    (hooks / "scripts" / "plugin-root-probe.sh").chmod(0o755)


def build(bundle: str, skill: str | None, prompt: Path | None, force: bool) -> int:
    ok, rejected = eligible(bundle)
    print(f"READINESS GATE — bundle '{bundle}': {len(ok)} PACKAGE NOW, {len(rejected)} below {PACKAGE_NOW_FLOOR}")
    for s in rejected:
        print(f"  excluded  {s.name:32s} {s.total:3d}  {s.decision}")
    if not ok:
        print("REFUSED: nothing in this bundle scores PACKAGE NOW. "
              "Packaging a REFERENCE-ONLY workflow proves nothing.")
        return 1

    name = f"antigravity-{bundle}"
    out = PLUGINS_DIR / name
    if out.exists():
        if not force:
            print(f"REFUSED: {out.relative_to(ROOT)} exists. Re-run with --force "
                  f"(plugins are regenerated, never hand-edited).")
            return 1
        shutil.rmtree(out)
    out.mkdir(parents=True)

    (out / ".claude-plugin").mkdir()
    (out / ".claude-plugin" / "plugin.json").write_text(json.dumps({
        "name": name,
        "version": "1.0.0",
        "description": f"Antigravity {bundle} bundle — regenerated from the repo by "
                       f"execution/plugin_build.py. Local install only; not published.",
        "author": {"name": "Farrice Cain"},
        "license": "UNLICENSED",
        "keywords": ["antigravity", bundle],
    }, indent=2) + "\n", encoding="utf-8")

    packaged = [c for c in (emit_command(s, out) for s in ok) if c]
    skills = []
    if skill:
        got = emit_skill(skill, out, prompt)
        if got:
            skills.append(got)
        else:
            print(f"  WARN skill '{skill}' not found — skipped")
    emit_hook(out)

    (out / "README.md").write_text(
        f"# {name}\n\n{BUILD_STAMP}\n\n"
        f"Build artifact. The repo is the source of truth — regenerate with:\n\n"
        f"```bash\npython3 execution/plugin_build.py build --bundle {bundle} --force\n```\n\n"
        f"Local install only. Not published to any marketplace.\n\n"
        f"- Commands: {len(packaged)}\n- Skills: {len(skills)}\n- Hooks: 1 (SessionStart probe)\n",
        encoding="utf-8")

    print(f"BUILT {out.relative_to(ROOT)} — {len(packaged)} command(s), "
          f"{len(skills)} skill(s), 1 hook")
    return 0


# ──────────────────────────────────────────────────────────────────────────
# validate
# ──────────────────────────────────────────────────────────────────────────

def validate(path: Path) -> int:
    """Structural gate. Deterministic checks only — no install required."""
    fails: List[str] = []
    checks: List[str] = []

    manifest = path / ".claude-plugin" / "plugin.json"
    if not manifest.exists():
        fails.append("missing .claude-plugin/plugin.json")
    else:
        try:
            data = json.loads(manifest.read_text(encoding="utf-8"))
            if not re.fullmatch(r"[a-z0-9]+(-[a-z0-9]+)*", data.get("name", "")):
                fails.append(f"manifest name not kebab-case: {data.get('name')!r}")
            else:
                checks.append(f"manifest name ok ({data['name']})")
            if not re.fullmatch(r"\d+\.\d+\.\d+", str(data.get("version", ""))):
                fails.append("version is not semver")
            else:
                checks.append(f"semver ok ({data['version']})")
        except Exception as e:
            fails.append(f"manifest unparseable: {e}")

    for bad in path.glob(".claude-plugin/commands"):
        fails.append(f"components must live at plugin root, not inside .claude-plugin: {bad}")

    cmds = list((path / "commands").glob("*.md"))
    checks.append(f"{len(cmds)} command(s)")
    for c in cmds:
        if not _read(c).startswith("---"):
            fails.append(f"command missing frontmatter: {c.name}")

    for sk in (path / "skills").glob("*/"):
        if not (sk / "SKILL.md").exists():
            fails.append(f"skill dir without SKILL.md: {sk.name}")
    checks.append(f"{len(list((path / 'skills').glob('*/')))} skill(s)")

    hooks = path / "hooks" / "hooks.json"
    if hooks.exists():
        blob = _read(hooks)
        if PLUGIN_ROOT_VAR not in blob:
            fails.append("hooks.json does not use ${CLAUDE_PLUGIN_ROOT}")
        else:
            checks.append("hooks use ${CLAUDE_PLUGIN_ROOT}")
        try:
            json.loads(blob)
        except Exception as e:
            fails.append(f"hooks.json unparseable: {e}")

    # Absolute-path leak: the failure that only shows up on someone else's machine.
    leaked = [p.relative_to(path) for p in path.rglob("*")
              if p.is_file() and p.suffix in {".md", ".json", ".sh"}
              and str(ROOT) in _read(p)]
    if leaked:
        fails.append(f"absolute repo paths leaked into: {', '.join(str(x) for x in leaked[:5])}")
    else:
        checks.append("no absolute repo paths")

    # Command shadowing: an installed plugin must not silently take over a
    # repo-native /command (F-REG).
    repo_cmds = {p.stem for p in (ROOT / ".claude" / "commands").glob("*.md")}
    shadow = sorted({c.stem for c in cmds} & repo_cmds)
    if shadow:
        checks.append(f"NOTE {len(shadow)} command name(s) also exist repo-native "
                      f"(expected for a repo-derived bundle; verify precedence on install): "
                      f"{', '.join(shadow[:4])}")

    print(f"PLUGIN VALIDATE — {path.relative_to(ROOT) if path.is_relative_to(ROOT) else path}")
    for c in checks:
        print(f"  [ok]   {c}")
    for f in fails:
        print(f"  [FAIL] {f}")
    print(f"  → {len(fails)} failure(s)")
    return 1 if fails else 0


def main() -> int:
    ap = argparse.ArgumentParser(description="Compile a repo bundle into an installable plugin.")
    sub = ap.add_subparsers(dest="cmd", required=True)
    b = sub.add_parser("build")
    b.add_argument("--bundle", required=True, choices=sorted(readiness.BUNDLE_CANDIDATES))
    b.add_argument("--skill", help="Repo skill to carry into the plugin.")
    b.add_argument("--prompt", help="prompts-v2 file to bundle with --skill.")
    b.add_argument("--force", action="store_true", help="Regenerate over an existing build.")
    v = sub.add_parser("validate")
    v.add_argument("path")
    c = sub.add_parser("clean")
    c.add_argument("path")
    args = ap.parse_args()

    if args.cmd == "build":
        return build(args.bundle, args.skill,
                     Path(args.prompt) if args.prompt else None, args.force)
    if args.cmd == "validate":
        return validate(Path(args.path).resolve())
    target = Path(args.path).resolve()
    if not target.is_relative_to(PLUGINS_DIR):
        print(f"REFUSED: clean only operates inside {PLUGINS_DIR.relative_to(ROOT)}/")
        return 1
    shutil.rmtree(target)
    print(f"removed {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
