#!/usr/bin/env python3
import os
import yaml
import re

SKILLS_DIR = "skills"
AGENTS_DIR = "agents"
SKILL_INDEX = "SKILL_INDEX.md"
AGENT_INDEX = "AGENT_INDEX.md"

def extract_frontmatter(file_path):
    with open(file_path, "r", encoding="utf-8") as f:
        content = f.read()
    
    match = re.match(r'^---\s*\n(.*?)\n---\s*\n', content, re.DOTALL)
    if match:
        try:
            return yaml.safe_load(match.group(1))
        except yaml.YAMLError:
            return {}
    return {}

def sync_skills():
    print("Syncing SKILL_INDEX.md...")
    skills = []
    
    for item in sorted(os.listdir(SKILLS_DIR)):
        skill_path = os.path.join(SKILLS_DIR, item)
        if os.path.isdir(skill_path):
            skill_md_path = os.path.join(skill_path, "SKILL.md")
            if os.path.isfile(skill_md_path):
                meta = extract_frontmatter(skill_md_path)
                
                # Count prompts
                prompts_dir = os.path.join(skill_path, "references", "prompts")
                prompt_count = 0
                if os.path.isdir(prompts_dir):
                    prompt_count = len([f for f in os.listdir(prompts_dir) if f.endswith(".md")])
                
                name = meta.get("name", item)
                desc = meta.get("description", "")
                keywords = meta.get("keywords", [])
                keyword_str = ", ".join(keywords) if isinstance(keywords, list) else keywords
                
                skills.append({
                    "slug": item,
                    "name": name,
                    "desc": desc,
                    "keywords": keyword_str,
                    "prompt_count": prompt_count
                })
    
    with open(SKILL_INDEX, "w", encoding="utf-8") as f:
        f.write("# Skill Registry Directory\n\n")
        f.write("> Auto-generated by sync_registries.py. **Do not edit manually**.\n>\n")
        f.write("> Use this index to identify the correct skill for a specific task. Read the skill's `SKILL.md` to load its methodology into context.\n\n")
        f.write("| Skill Slug | Expert Name | Domain/Keywords | Prompts |\n")
        f.write("|------------|-------------|-----------------|---------|\n")
        for s in skills:
            f.write(f"| `{s['slug']}` | **{s['name']}** | {s['keywords']} | {s['prompt_count']} |\n")
            
    print(f"✅ Synced {len(skills)} valid skills to SKILL_INDEX.md.")

def sync_agents():
    print("Syncing AGENT_INDEX.md...")
    agents = []
    
    for item in sorted(os.listdir(AGENTS_DIR)):
        agent_path = os.path.join(AGENTS_DIR, item)
        if os.path.isdir(agent_path):
            agent_md_path = os.path.join(agent_path, "AGENT.md")
            if os.path.isfile(agent_md_path):
                meta = extract_frontmatter(agent_md_path)
                name = meta.get("name", item)
                desc = meta.get("description", "")
                keywords = meta.get("keywords", [])
                keyword_str = ", ".join(keywords) if isinstance(keywords, list) else keywords
                
                agents.append({
                    "slug": item,
                    "name": name,
                    "desc": desc,
                    "keywords": keyword_str
                })
                
    with open(AGENT_INDEX, "w", encoding="utf-8") as f:
        f.write("# Agent Registry Directory\n\n")
        f.write("> Auto-generated by sync_registries.py. **Do not edit manually**.\n>\n")
        f.write("> Use this index to find the right expert alias for a specific task. Remember, agents embody methodologies.\n\n")
        f.write("| Agent Slug | Persona | Domain/Keywords |\n")
        f.write("|------------|---------|-----------------|\n")
        for a in agents:
            f.write(f"| `{a['slug']}` | **{a['name']}** | {a['keywords']} |\n")
            
    print(f"✅ Synced {len(agents)} valid agents to AGENT_INDEX.md.")

if __name__ == "__main__":
    if not os.path.exists(SKILLS_DIR) or not os.path.exists(AGENTS_DIR):
        print("Run this from the workspace root.")
        exit(1)
        
    try:
        import yaml
    except ImportError:
        print("PyYAML required. Please pip install pyyaml.")
        exit(1)
        
    sync_skills()
    sync_agents()
