#!/usr/bin/env python3
"""Wire 'Execution Prompts' pointer sections into SKILL.md files.

Deterministic, idempotent: for every skill with structure-pure v2 prompts in
.agent/prompt-index.json, insert (or refresh) a marker-delimited section at
the end of its SKILL.md listing every v2 prompt (title + path). Re-running
replaces the section in place; skills that gain prompts later just need a
re-run. No LLM in the loop.

Usage:
  python3 execution/wire_prompt_pointers.py            # dry-run report
  python3 execution/wire_prompt_pointers.py --write    # apply
"""
import argparse
import json
import os
from collections import defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INDEX = os.path.join(ROOT, ".agent", "prompt-index.json")
BEGIN = "<!-- BEGIN:execution-prompts (generated by execution/wire_prompt_pointers.py — do not hand-edit; re-run to refresh) -->"
END = "<!-- END:execution-prompts -->"


def build_section(skill, entries):
    lines = [
        BEGIN,
        "",
        "## Execution Prompts (structure-pure v2)",
        "",
        f"{len(entries)} deterministic practitioner prompts — each carries an Output Contract, "
        "Output Skeleton, and Quality Gate. When a deliverable matches one, Read it and honor its "
        "contract instead of improvising the output shape.",
        "",
    ]
    for e in sorted(entries, key=lambda x: x.get("path", "")):
        rel = e.get("path", "")
        title = e.get("title", os.path.basename(rel))
        lines.append(f"- **{title}** — `{rel}`")
    lines += ["", END, ""]
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    args = ap.parse_args()

    entries = json.load(open(INDEX)).get("entries", [])
    by_skill = defaultdict(list)
    for e in entries:
        if e.get("kind") == "prompt-v2" and e.get("path", "").startswith("skills/"):
            by_skill[e["skill"]].append(e)

    wired = updated = missing_skillmd = 0
    for skill, es in sorted(by_skill.items()):
        skill_md = os.path.join(ROOT, "skills", skill, "SKILL.md")
        if not os.path.exists(skill_md):
            missing_skillmd += 1
            print(f"SKIP (no SKILL.md): {skill}")
            continue
        text = open(skill_md, encoding="utf-8").read()
        section = build_section(skill, es)
        if BEGIN in text:
            pre = text.split(BEGIN)[0]
            post = text.split(END, 1)[1] if END in text else ""
            new = pre + section + post.lstrip("\n")
            action = "refresh"
            updated += 1
        else:
            new = text.rstrip("\n") + "\n\n" + section
            action = "add"
            wired += 1
        if args.write:
            open(skill_md, "w", encoding="utf-8").write(new)
        print(f"{action}: {skill} ({len(es)} prompts)")

    mode = "WROTE" if args.write else "DRY-RUN"
    print(f"\n{mode}: {wired} added · {updated} refreshed · {missing_skillmd} missing SKILL.md · {len(by_skill)} skills total")


if __name__ == "__main__":
    main()
